Repository Codeminer42/Punchclock, pull requests merged in 2023-11, with the labels that each got.

#590 Implementing professional experience create
  app/controllers/application_controller.rb
  app/controllers/professional_experiences_controller.rb
  app/views/professional_experiences/_form.html.erb
  app/views/professional_experiences/index.html.erb
  app/views/professional_experiences/new.html.erb
  config/locales/pt-BR/pt-BR.yml
  config/locales/pt-BR/views.yml
  spec/controllers/new_admin/revenue_forecast_controller_spec.rb
  spec/features/new_admin/revenue_forecast_spec.rb
  spec/requests/professional_experiences_spec.rb
Labels: resume

#591 Professional experiences show
  app/controllers/professional_experiences_controller.rb
  app/views/professional_experiences/index.html.erb
  app/views/professional_experiences/show.html.erb
  config/locales/pt-BR/pt-BR.yml
  spec/requests/professional_experiences_spec.rb
Labels: resume

#592 Professional experiences update
  app/controllers/professional_experiences_controller.rb
  app/views/professional_experiences/edit.html.erb
  app/views/professional_experiences/index.html.erb
  app/views/professional_experiences/show.html.erb
  spec/requests/professional_experiences_spec.rb
Labels: resume

#589 feat: talks index page
  app/controllers/talks_controller.rb
  app/views/talks/_table.html.erb
  app/views/talks/index.html.erb
  config/locales/pt-BR/views.yml
  config/routes.rb
  spec/features/index_talks_spec.rb
  spec/requests/talks_controller_spec.rb
Labels: enhancement, resume

#594 implementing destroy method
  app/controllers/professional_experiences_controller.rb
  app/views/professional_experiences/index.html.erb
  app/views/professional_experiences/show.html.erb
  config/locales/pt-BR/views.yml
  spec/requests/professional_experiences_spec.rb
Labels: resume

#578 Feat/education experience index
  app/admin/education_experiences.rb
  app/controllers/education_experiences_controller.rb
  app/decorators/education_experience_decorator.rb
  app/models/education_experience.rb
  app/spreadsheets/education_experiences_spreadsheet.rb
  app/views/education_experiences/index.html.erb
  app/views/refills/_navigation.html.erb
  config/locales/pt-BR/pt-BR.yml
  config/routes.rb
  spec/controllers/education_experiences_controller_spec.rb
  spec/decorators/education_experience_decorator_spec.rb
  spec/features/admin/education_experiences_spec.rb
  spec/features/navigation_bar_spec.rb
  spec/models/education_experience_spec.rb
  spec/spreadsheets/education_experiences_spreadsheet_spec.rb
Labels: resume

#600 Implementing show for talks
  app/controllers/talks_controller.rb
  app/views/talks/_table.html.erb
  app/views/talks/show.html.erb
  config/locales/pt-BR/pt-BR.yml
  config/routes.rb
  spec/requests/talks_controller_spec.rb
Labels: resume

#585 Feat/education experience create
  app/controllers/education_experiences_controller.rb
  app/views/education_experiences/_form.html.erb
  app/views/education_experiences/index.html.erb
  app/views/education_experiences/new.html.erb
  config/locales/pt-BR/responders.yml
  config/locales/pt-BR/views.yml
  spec/controllers/education_experiences_controller.rb
  spec/controllers/education_experiences_controller_spec.rb
  spec/features/dashboard_spec.rb
  spec/features/new_education_experience_spec.rb
Labels: resume

#596 Feat/education experience destroy
  app/controllers/education_experiences_controller.rb
  app/decorators/education_experience_pagination_decorator.rb
  app/models/education_experience.rb
  app/views/education_experiences/index.html.erb
  config/locales/pt-BR/views.yml
  spec/features/edit_education_experience_spec.rb
  spec/features/navigation_bar_spec.rb
  spec/models/education_experience_spec.rb
  spec/requests/education_experiences_spec.rb
Labels: resume

#599 implementing show for education experience
  app/controllers/education_experiences_controller.rb
  app/views/education_experiences/index.html.erb
  app/views/education_experiences/show.html.erb
  config/locales/pt-BR/pt-BR.yml
  spec/features/edit_education_experience_spec.rb
  spec/features/navigation_bar_spec.rb
  spec/requests/education_experiences_spec.rb
Labels: resume

#560 feat: add new admin repositories index page
  app/controllers/new_admin/repositories_controller.rb
  app/models/ability_admin.rb
  app/models/repository.rb
  app/queries/new_admin/repository_query.rb
  app/views/application/_sidebar.html.erb
  app/views/new_admin/repositories/_repositories_filters.html.erb
  app/views/new_admin/repositories/_repositories_table.html.erb
  app/views/new_admin/repositories/index.html.erb
  config/locales/pt-BR/pt-BR.yml
  config/locales/pt-BR/views.yml
  config/routes.rb
  spec/models/repository_spec.rb
  spec/queries/new_admin/repository_query_spec.rb
  spec/requests/new_admin/repositories_controller_spec.rb
Labels: enhancement, new admin

#580 Create questionnaires new admin
  app/controllers/new_admin/questionnaires_controller.rb
  app/javascript/controllers/nested_form_controller.js
  app/javascript/packs/questionnaire.js
  app/views/layouts/new_admin.html.erb
  app/views/new_admin/questionnaires/_form.html.erb
  app/views/new_admin/questionnaires/_question_form.html.erb
  app/views/new_admin/questionnaires/_questionnaires_filter.html.erb
  app/views/new_admin/questionnaires/_questionnaires_table.html.erb
  app/views/new_admin/questionnaires/index.html.erb
  app/views/new_admin/questionnaires/new.html.erb
  config/locales/pt-BR/pt-BR.yml
  package.json
  spec/queries/new_admin/questionnaires_query_spec.rb
  spec/requests/new_admin/questionnaires_controller_spec.rb
  yarn.lock
Labels: new admin
